---
name: "Kitsu"
guid: "88d809e2-056b-47f4-9911-073949b9963f"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-kitsu.png"
version: 4
targetAbi: "10.7.7.0"
framework: "net6.0"
overview: "Kitsu metadata provider"
description: >
  Kitsu metadata provider

category: "Metadata"
owner: "jellyfin"
artifacts:
  - "Jellyfin.Plugin.Kitsu.dll"
changelog: |2-
  ### Code or Repo Maintenance ###
  - Use meta ci (#14) @crobibero

  ### CI & build changes ###
  - fix: meta ci workflows (#17) @h1dden-da3m0n
  - Use meta ci (#14) @crobibero
